
---
- name: Install Apache HTTP server
  hosts: g2
  become: yes

  tasks:
    - name: Install Apache on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure Apache is running on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Apache on CentOS
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Ensure Apache is running on CentOS
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'RedHat'          
...
