---
- name: Install httpd server
  hosts: n2
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: start
      service:
        name: httpd
        state: started

    - name: enable httpd
      service:
        name: httpd
        enabled: yes
...





