
---
- name: Install httpd
  hosts: g1
  become: yes

  tasks:
    - name: Install httpd on linux
      yum:
        name: httpd
        state: present

    - name: Ensure httpd is running on Ubuntu
      service:
        name: httpd
        state: started 

    - name: Ensure httpd is running on Ubuntu
      service:
        name: httpd
        enabled: yes        
...
