---
- name: Deploy web app
  hosts: g1
  become: yes

  tasks:
    - name: Install git
      yum:
        name: git
        state: present

    - name: Host code
      git:
        repo: https://github.com/Etimdevops/ecomm-3.git
        dest: /var/www/html
        force: yes
...





