---
- name: Deploy web app
  hosts: n3
  become: yes

  tasks:
    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install Apache HTTP Server
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache HTTP Server
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Clone application repository
      git:
        repo: https://github.com/Etimdevops/food3.git
        dest: /var/www/html
...





