
---
  - name: Install Apache HTTP server
  hosts: g2
  become: yes

  tasks:
    - name: Install Apache on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Ensure Apache is running on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache on CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Centos"

    - name: Ensure Apache is running on CentOS
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Centos"       
...
