---
- name: Install dnf on CentOS 7
  hosts: all
  become: yes
  tasks:
    - name: Ensure the system is CentOS 7
      assert:
        that:
          - ansible_distribution == "CentOS"
          - ansible_distribution_major_version == "7"
        fail_msg: "This playbook only supports CentOS 7."

    - name: Update all yum packages
      yum:
        name: "*"
        state: latest

    - name: Install dnf package
      yum:
        name: dnf
        state: present
        when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" 

    - name: Verify dnf installation
      command: dnf --version
      register: dnf_version
      ignore_errors: yes

    - name: Display dnf version
      debug:
        msg: "DNF version installed: {{ dnf_version.stdout }}"

...