---
- name: Variables Demo
  hosts: n6
  become: yes
  vars:
    myusername: EtimDevops
    myusername: Sherlyna

  tasks:
    - name: update dynamic page
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
        force: yes
...